{
 "title": "Otus lesson-07 - grafana",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "nginx - Error 500",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[2m]))"
    }
   ]
  },
  {
   "title": "Error 500 /user",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(otus_sa_error_500_counter[2m]))"
    }
   ]
  },
  {
   "title": "nginx RPS /user",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_request_duration_seconds_count[2m]))"
    }
   ]
  },
  {
   "title": "RPS /user",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(otus_sa_requests_latency_count{exported_endpoint=\"/user\", method=\"POST\"}[2m]))",
     "legendFormat": "POST: /user"
    },
    {
     "expr": "sum(rate(otus_sa_requests_latency_count{exported_endpoint=\"/user/{id}\", method=\"GET\"}[2m]))",
     "legendFormat": "GET: /user/{id}"
    },
    {
     "expr": "sum(rate(otus_sa_requests_latency_count{exported_endpoint=\"/user/{id}\", method=\"DELETE\"}[2m]))",
     "legendFormat": "DELETE: /user/{id}"
    },
    {
     "expr": "sum(rate(otus_sa_requests_latency_count{exported_endpoint=\"/user/{id}\", method=\"PUT\"}[2m]))",
     "legendFormat": "PUT: /user"
    }
   ]
  },
  {
   "title": "nginx Latency (response time) 0.5 /user",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.5 /user",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(otus_sa_requests_latency_bucket{exported_endpoint=\"/user\", method=\"POST\"}[2m]))) * 1000",
     "legendFormat": "POST: /user"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(otus_sa_requests_latency_bucket{exported_endpoint=\"/user/{id}\", method=\"GET\"}[2m]))) * 1000",
     "legendFormat": "GET: /user/{id}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(otus_sa_requests_latency_bucket{exported_endpoint=\"/user/{id}\", method=\"DELETE\"}[2m]))) * 1000",
     "legendFormat": "DELETE: /user/{id}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le)(rate(otus_sa_requests_latency_bucket{exported_endpoint=\"/user/{id}\", method=\"PUT\"}[2m]))) * 1000",
     "legendFormat": "PUT: /user/{id}"
    }
   ]
  },
  {
   "title": "nginx Latency (response time) 0.95 /user",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.95 /user",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(otus_sa_requests_latency_bucket{exported_endpoint=\"/user\", method=\"POST\"}[2m]))) * 1000",
     "legendFormat": "POST: /user"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(otus_sa_requests_latency_bucket{exported_endpoint=\"/user/{id}\", method=\"GET\"}[2m]))) * 1000",
     "legendFormat": "GET: /user/{id}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(otus_sa_requests_latency_bucket{exported_endpoint=\"/user/{id}\", method=\"DELETE\"}[2m]))) * 1000",
     "legendFormat": "DELETE: /user/{id}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le)(rate(otus_sa_requests_latency_bucket{exported_endpoint=\"/user/{id}\", method=\"PUT\"}[2m]))) * 1000",
     "legendFormat": "PUT: /user/{id}"
    }
   ]
  },
  {
   "title": "nginx Latency (response time) 0.99 /user",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(nginx_ingress_controller_request_duration_seconds_bucket[2m]))) * 1000"
    }
   ]
  },
  {
   "title": "Latency (response time) 0.99 /user",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(otus_sa_requests_latency_bucket{exported_endpoint=\"/user\", method=\"POST\"}[2m]))) * 1000",
     "legendFormat": "POST: /user"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(otus_sa_requests_latency_bucket{exported_endpoint=\"/user/{id}\", method=\"GET\"}[2m]))) * 1000",
     "legendFormat": "GET: /user/{id}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(otus_sa_requests_latency_bucket{exported_endpoint=\"/user/{id}\", method=\"DELETE\"}[2m]))) * 1000",
     "legendFormat": "DELETE: /user/{id}"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le)(rate(otus_sa_requests_latency_bucket{exported_endpoint=\"/user/{id}\", method=\"PUT\"}[2m]))) * 1000",
     "legendFormat": "PUT: /user/{id}"
    }
   ]
  }
 ]
}