
replicaCount: 1

image:
  repository: vadimshtukan/notification-chart

metrics:
  serviceMonitor:
    enabled: false

service:
  type: NodePort
  port: 8005
  targetPort: 8005

ingress:
  enabled: false

