{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "otus-sa-vadimshtukan-chart.fullname" . }}-servicemonitor
  labels:
  {{- include "otus-sa-vadimshtukan-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "otus-sa-vadimshtukan-chart.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "otus-sa-vadimshtukan-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      targetPort: 8000
      path: /metrics
    - interval: 30s
      targetPort: 8000
      path: /metrics_system
{{- end }}
