server:
  port: 8000
---
app:
  services:
    key: http://127.0.0.1:8001
    ettn: http://127.0.0.1:8002

---
#spring:
#  cloud:
#    gateway:
##      default-filters:
##        - name: SCGWGlobalFilter
#      routes:
#        - id: identity
#          uri: http://127.0.0.1:${SERVER_PORT}
##          uri: http://localhost:9090
#          predicates:
#            - Path=/identity/user/**
#            - Method=GET
#          filters:
##            - name: RegistrationPreFilter
##            - name: RegistrationPostFilter
#            - RewritePath=/identity/user/(?<userId>.*), /identity/user/${userId}
##            - name: SCGWPostFilter