
replicaCount: 1

image:
  repository: vadimshtukan/api-getaway-web-chart

metrics:
  serviceMonitor:
    enabled: true

service:
  type: NodePort
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  host: arch.homework
