# Default values for lesson7-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
    repository: vadimshtukan/otus-sa-l7

service:
  type: NodePort
  port: 80
  targetPort: 8000

externalMySql:
#  username: cm9vdA==
  username: root

ingress:
  enabled: true
#  host: arch.homework
  hosts:
    - host: arch.homework
      paths: ["/app"]

metrics:
  serviceMonitor:
    enabled: true

mysql:
  imageTag: 5.7.9
  #  password: cDEyMzQ1Ng==
  mysqlRootPassword: p123456
  mysqlDatabase: otus_vadim_shtukan_db
  persistence:
    size: 200Mi