apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lesson-09-chart.fullname" . }}-config
data:
{{/*  spring.datasource.url: jdbc:mysql://{{ .Release.Name }}-mysql:3306/{{ .Values.mysql.mysqlDatabase }}*/}}
{{/*  mysql.darabase: {{ .Values.mysql.mysqlDatabase }}*/}}
  server.port: "9090"
  app.fusionauth.host: {{ .Values.fusionauth.host }}
  app.fusionauth.authorizationToken: {{ .Values.fusionauth.authorizationToken }}
  app.fusionauth.applicationId: {{ .Values.fusionauth.applicationId }}
  app.fusionauth.jwtKeySecret: {{ .Values.fusionauth.jwtKeySecret }}
{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: Secret*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "lesson-09-chart.fullname" . }}-config-secret*/}}
{{/*data:*/}}
{{/*  spring.datasource.username: {{ .Values.externalMySql.username | b64enc | quote }}*/}}
{{/*  spring.datasource.password: {{ .Values.mysql.mysqlRootPassword | b64enc | quote }}*/}}

