apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "lesson-09-chart.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}($|/)(.*)
        {{- end }}
  {{- end }}
            backend:
              serviceName: {{ include "lesson-09-chart.name" . }}
              servicePort: {{ .Values.service.port }}
          - path: /identity($|/)(.*)
            backend:
              serviceName: fusionauth-helm
              servicePort: 9012