# Default values for lesson7-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
    repository: vadimshtukan/otus-sa-l22

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingress:
  enabled: true
#  host: arch.homework
  hosts:
    - host: arch.homework
      paths: ["/app"]

metrics:
  serviceMonitor:
    enabled: true

mongo:
  host: mongo-mongodb
  port: 27017
  username: user
  password: p123456
  database: cart
