apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "otus-sa-vadimshtukan-chart.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /otusapp($|/)(.*)
            backend:
              serviceName: {{ include "otus-sa-vadimshtukan-chart.name" . }}
              servicePort: {{ .Values.service.port }}
