{
 "title": "eTTN",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Key service latency (login)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, (sum by (le) (rate(key_user_controller_latency_bucket{UserController=\"login\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Total Error (500)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gateway_requests_seconds_count{httpStatusCode=\"500\"}[1m]))"
    }
   ]
  },
  {
   "title": "Key service latency (registration)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, (sum by (le) (rate(key_user_controller_latency_bucket{UserController=\"registration\"}[1m]))))"
    }
   ]
  },
  {
   "title": "Total OK (200)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(gateway_requests_seconds_count{httpStatusCode=\"200\"}[1m]))"
    }
   ]
  }
 ]
}