image:
  repository: fusionauth/fusionauth-app
  tag: 1.16.0

service:
  type: NodePort
  port: 9012

database:
  protocol: postgresql
  host: "fusionauth-db-postgresql"
  port: 5432
  tls: false
  tlsMode: require
  name: fusionauth_db

  # To use an existing secret, set `existingSecret` to the name of the secret. We expect two keys: `password` and `rootpassword`
  user: "fusionauth"
  password: "p123456"
  # These credentials are used for bootstrapping the database
  root:
    user: "fusionauth"
    password: "p123456"


search:
  # Valid values for engine are 'elasticsearch' or (if you are using fusionauth >= 1.16.0-rc.1) 'database'.
  engine: database
#  protocol: http
#  host: "dddd"
#  port: 9200
  # user: ""
  # password: ""

