apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "otus-sa-vadimshtukan-chart.fullname" . }}-config
data:
  spring.datasource.url: jdbc:mysql://{{ .Release.Name }}-mysql:3306/{{ .Values.mysql.mysqlDatabase }}
  mysql.darabase: {{ .Values.mysql.mysqlDatabase }}
  cache.type: {{ .Values.cache_r.type }}
  cache.redis.host: {{ .Values.cache_r.redis.host }}
  cache.redis.port: "{{ .Values.cache_r.redis.port }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "otus-sa-vadimshtukan-chart.fullname" . }}-config-secret
data:
  spring.datasource.username: {{ .Values.externalMySql.username | b64enc | quote }}
  spring.datasource.password: {{ .Values.mysql.mysqlRootPassword | b64enc | quote }}
  cache.redis.password: {{ .Values.cache_r.redis.password | b64enc | quote  }}

