swagger: '2.0'
info:
  description: eTTN API
  version: 1.0.0
  title: eTTN API ref (for Web)

  contact:
    email: vadim.shtukan@gmail.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html


# tags are used for organizing operations
tags:
  - name: Identity
    description: Регистрация, аутентификация и авторизация пользователей


paths:
  /identity/user/login:
    post:
      tags:
        - Identity
      summary: User login
      description: Аутентификация пользователя(получения токена)
      produces:
        - application/json
      parameters:
        - in: body
          name: UserRegistration
          description: Данные для входа. Необходимо заполнить  UserRegistration.signature
          schema:
            $ref: '#/definitions/UserRegistration'
          required: true
      responses:
        200:
          description: Аутентификация прошла успешно
          schema:
            $ref:  '#/definitions/UserLogin'
        403:
          description: Не удалось авторизоваться
  /identity/user:
    post:
      tags:
        - Identity
      summary: Create new user
      description: Зарегистрировать нового пользователя. Зарегистрироваться может любой пользователь, при этом у него не будет ни каких прав. |
              Права может выдать ответсвенное лицо в организации, у которого есть договор с нами.
      produces:
        - application/json
      parameters:
        - in: body
          name: UserRegistration
          description: Информация о пользователе
          schema:
            $ref: '#/definitions/UserRegistration'
          required: true
      responses:
        201:
          description: Пользователь создан
          schema:
            $ref:  '#/definitions/UserLogin'

definitions:
  UserLogin:
    type: object
    properties:
      userId:
        type: string
      jwt:
        type: string
  Company:
    type: object
    properties:
      id:
        type: string
        format: uuid
      egrpo:
        type: string
      name:
        type: string

  UserRegistration:
    type: object
    properties:
      id:
        type: string
        format: uuid
      company:
        $ref: '#/definitions/Company'
      signature:
        type: string
        description: Серийный номер ЭЦП, подписанная ЭЦП. Должен быть подписан не позже 1 минуты до выполнения запроса.
      email:
        type: string
        format: email
      firstName:
        type: string
      lastName:
        type: string
      mobilePhone:
        type: string


# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /ppl33-35/eTTN/1.0.0
schemes:
  - https