apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ include "api-getaway-web-chart.fullname" . }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /web($|/)(.*)
            backend:
              serviceName: {{ include "api-getaway-web-chart.name" . }}
              servicePort: {{ .Values.service.port }}