apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-getaway-web-chart.name" . }}
  labels:
    {{- include "api-getaway-web-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "api-getaway-web-chart.selectorLabels" . | nindent 4 }}
