{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "api-getaway-web-chart.fullname" . }}-servicemonitor
  labels:
  {{- include "api-getaway-web-chart.labels" . | nindent 4 }}
spec:
  jobLabel: {{ include "api-getaway-web-chart.fullname" . }}
  namespaceSelector:
    matchNames:
      - "{{ $.Release.Namespace }}"
  selector:
    matchLabels:
      {{- include "api-getaway-web-chart.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: 15s
      targetPort: 8000
      path: /actuator/metrics
{{/*    - interval: 30s*/}}
{{/*      targetPort: 8000*/}}
{{/*      path: /metrics_system*/}}
{{- end }}
