apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lesson7-chart.fullname" . }}
  labels:
    {{- include "lesson7-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "lesson7-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lesson7-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "lesson7-chart.fullname" . }}-config-secret
                  key: spring.datasource.password
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "lesson7-chart.fullname" . }}-config-secret
                  key: spring.datasource.username
#                  key: mysql.db.name
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lesson7-chart.fullname" . }}-config
                  key: spring.datasource.url
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              port: {{ .Values.service.targetPort }}
              path: /health
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
              httpGet:
                port: {{ .Values.service.targetPort }}
                path: /health
              initialDelaySeconds: 40
              periodSeconds: 10

